version: '3.8'

services:
  server:
    image: node:12-alpine
    command: sh -c ". start.sh"
    restart: always
    ports:
      - 5000:5000
    working_dir: /todo-server
    environment:
      SECRET_TOKEN: ${SECRET_TOKEN}

    volumes:
      - ./:/todo-server
      - /todo-server/node_modules

  db:
    depends_on:
      - server
    image: postgres
    restart: always
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
