version: '3.8'

services:
  server:
    container_name: todo-server
    command: sh -c '. /todo-server/app/start.sh'
    image: node:12-alpine
    working_dir: /todo-server
    restart: always
    # build: .
    volumes:
      #ignores node_modules van host
      - node_modules:/todo-server/app/node_modules
      - ./:/todo-server/app
      #Alles van deze folder naar /todo-server/app/
      #BIND volume
    environment:
      SERVER_HOST: postgres
      SECRET_TOKEN: ${SECRET_TOKEN}
    ports:
      - '5000:5000'
    links:
      - db
  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #moet secret worden
      POSTGRES_USER: ${POSTGRES_USER}
      #moet secret worden
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
  node_modules:
